In [57]:
import pandas as pd
import json
import math
import numpy as np

# Load dataset (Replace this with your actual dataset file path)
df = pd.read_csv('sample_data.csv')

In [58]:
df.fillna(0, inplace=True)

In [59]:
df.head()

,Name,University,Category,Total Runs,Balls Faced,Innings Played,Wickets,Overs Bowled,Runs Conceded
0,Chamika Chandimal,University of the Visual & Performing Arts,Batsman,530,588,10,0,3,21
1,Dimuth Dhananjaya,University of the Visual & Performing Arts,All-Rounder,250,208,10,8,40,240
2,Avishka Mendis,Eastern University,All-Rounder,210,175,7,7,35,210
3,Danushka Kumara,University of the Visual & Performing Arts,Batsman,780,866,15,0,5,35
4,Praveen Vandersay,Eastern University,Batsman,329,365,7,0,3,24

In [60]:
df1 = pd.DataFrame()

In [61]:
# Calculate Batting Metrics
df1["Name"] = df["Name"]
df1["University"] = df["University"]
df1["Category"] = df["Category"]


df1["Strike Rate"] = (df["Total Runs"] / df["Balls Faced"]) * 100
df1["Batting Average"] = df["Total Runs"] / df["Innings Played"]
df1["Bowling Strike Rate"] = df["Overs Bowled"]*6 / df["Wickets"]
df1["Economy Rate"] = (df["Runs Conceded"] / df["Overs Bowled"]*6)*6

In [62]:
df1.replace([np.inf, -np.inf], 0, inplace=True)
df1.head()

,Name,University,Category,Strike Rate,Batting Average,Bowling Strike Rate,Economy Rate
0,Chamika Chandimal,University of the Visual & Performing Arts,Batsman,90.136054,53.0,0.0,252.0
1,Dimuth Dhananjaya,University of the Visual & Performing Arts,All-Rounder,120.192308,25.0,30.0,216.0
2,Avishka Mendis,Eastern University,All-Rounder,120.000000,30.0,30.0,216.0
3,Danushka Kumara,University of the Visual & Performing Arts,Batsman,90.069284,52.0,0.0,252.0
4,Praveen Vandersay,Eastern University,Batsman,90.136986,47.0,0.0,288.0

In [63]:
def calculate_player_points(row):
    if row["Bowling Strike Rate"] == 0:
        if row["Economy Rate"] == 0:
            return (row["Strike Rate"] / 5 + row["Batting Average"] * 0.8)
        else:
            return (row["Strike Rate"] / 5 + row["Batting Average"] * 0.8) + (500 / row["Economy Rate"])
    else:
        if row["Economy Rate"] == 0:
            return (row["Strike Rate"] / 5 + row["Batting Average"] * 0.8) - (500 / row["Bowling Strike Rate"])
        else:
            return (row["Strike Rate"] / 5 + row["Batting Average"] * 0.8) - (500 / row["Bowling Strike Rate"] + 140 / row["Economy Rate"])

df1["Player Points"] = df1.apply(calculate_player_points, axis=1)

df1["Player Points"] = abs(df1["Player Points"])

df1["Value"] = round((9 * df1["Player Points"] + 100) * 1000 / 50000) * 50000

In [64]:
df1 = df1.reset_index(drop=True)
df = df.reset_index(drop=True)

In [65]:
df1.replace([np.inf, -np.inf], 0, inplace=True)
df1.head(20)

,Name,University,Category,Strike Rate,Batting Average,Bowling Strike Rate,Economy Rate,Player Points,Value
0,Chamika Chandimal,University of the Visual & Performing Arts,Batsman,90.136054,53.0,0.000000,252.0,62.411338,650000.0
1,Dimuth Dhananjaya,University of the Visual & Performing Arts,All-Rounder,120.192308,25.0,30.000000,216.0,26.723647,350000.0
2,Avishka Mendis,Eastern University,All-Rounder,120.000000,30.0,30.000000,216.0,30.685185,400000.0
3,Danushka Kumara,University of the Visual & Performing Arts,Batsman,90.069284,52.0,0.000000,252.0,61.597984,650000.0
4,Praveen Vandersay,Eastern University,Batsman,90.136986,47.0,0.000000,288.0,57.363508,600000.0
5,Niroshan Mathews,University of the Visual & Performing Arts,Batsman,90.163934,55.0,0.000000,324.0,63.575997,650000.0
6,Chaturanga Gunathilaka,University of Moratuwa,Bowler,50.000000,12.0,18.206897,216.0,8.510269,200000.0
7,Lahiru Rathnayake,University of Ruhuna,Batsman,90.048544,53.0,0.000000,288.0,62.145820,650000.0
8,Jeewan Thirimanne,University of Jaffna,Batsman,90.069284,52.0,0.000000,288.0,61.349968,650000.0
9,Kalana Samarawickrama,Eastern University,Batsman,90.099010,52.0,0.000000,288.0,61.355913,650000.0
10,Lakshan Vandersay,University of the Visual & Performing Arts,All-Rounder,120.178042,27.0,30.000000,216.0,28.320793,350000.0
11,Roshen Samarawickrama,University of Kelaniya,Bowler,50.000000,10.0,18.260870,144.0,10.353175,200000.0
12,Sammu Sandakan,University of Ruhuna,Bowler,50.000000,12.0,18.461538,144.0,8.455556,200000.0
13,Kalana Jayawardene,University of Jaffna,Bowler,50.000000,12.0,18.181818,144.0,8.872222,200000.0
14,Binura Samarawickrama,University of the Visual & Performing Arts,Bowler,50.000000,11.0,18.000000,144.0,9.950000,200000.0
15,Dasun Thirimanne,Eastern University,Bowler,50.000000,11.0,18.206897,180.0,9.439899,200000.0
16,Angelo Samarawickrama,University of Kelaniya,Batsman,90.021231,53.0,0.000000,252.0,62.388373,650000.0
17,Nuwan Jayawickrama,University of Ruhuna,Batsman,90.090090,50.0,0.000000,324.0,59.561228,650000.0
18,Kusal Dhananjaya,South Eastern University,Batsman,90.056285,48.0,0.000000,288.0,58.147368,600000.0
19,Chamika Bandara,Eastern University,Batsman,90.000000,54.0,0.000000,324.0,62.743210,650000.0

In [66]:
df1.to_json("cricket_data.json", orient="records", indent=4)

print("JSON file saved successfully!")

JSON file saved successfully!

In [67]:
import json

# Open and read the JSON file
with open("cricket_data.json", "r") as file:
    data = json.load(file)

# Print JSON data
print(json.dumps(data, indent=4))  # Pretty-print JSON

[
    {
        "Name": "Chamika Chandimal",
        "University": "University of the Visual & Performing Arts",
        "Category": "Batsman",
        "Strike Rate": 90.1360544218,
        "Batting Average": 53.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 252.0,
        "Player Points": 62.4113378685,
        "Value": 650000.0
    },
    {
        "Name": "Dimuth Dhananjaya",
        "University": "University of the Visual & Performing Arts",
        "Category": "All-Rounder",
        "Strike Rate": 120.1923076923,
        "Batting Average": 25.0,
        "Bowling Strike Rate": 30.0,
        "Economy Rate": 216.0,
        "Player Points": 26.7236467236,
        "Value": 350000.0
    },
    {
        "Name": "Avishka Mendis",
        "University": "Eastern University",
        "Category": "All-Rounder",
        "Strike Rate": 120.0,
        "Batting Average": 30.0,
        "Bowling Strike Rate": 30.0,
        "Economy Rate": 216.0,
        "Player Points": 30.6851851852,
        "Value": 400000.0
    },
    {
        "Name": "Danushka Kumara",
        "University": "University of the Visual & Performing Arts",
        "Category": "Batsman",
        "Strike Rate": 90.0692840647,
        "Batting Average": 52.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 252.0,
        "Player Points": 61.5979837971,
        "Value": 650000.0
    },
    {
        "Name": "Praveen Vandersay",
        "University": "Eastern University",
        "Category": "Batsman",
        "Strike Rate": 90.1369863014,
        "Batting Average": 47.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 288.0,
        "Player Points": 57.3635083714,
        "Value": 600000.0
    },
    {
        "Name": "Niroshan Mathews",
        "University": "University of the Visual & Performing Arts",
        "Category": "Batsman",
        "Strike Rate": 90.1639344262,
        "Batting Average": 55.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 63.5759967618,
        "Value": 650000.0
    },
    {
        "Name": "Chaturanga Gunathilaka",
        "University": "University of Moratuwa",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 12.0,
        "Bowling Strike Rate": 18.2068965517,
        "Economy Rate": 216.0,
        "Player Points": 8.5102693603,
        "Value": 200000.0
    },
    {
        "Name": "Lahiru Rathnayake",
        "University": "University of Ruhuna",
        "Category": "Batsman",
        "Strike Rate": 90.0485436893,
        "Batting Average": 53.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 288.0,
        "Player Points": 62.145819849,
        "Value": 650000.0
    },
    {
        "Name": "Jeewan Thirimanne",
        "University": "University of Jaffna",
        "Category": "Batsman",
        "Strike Rate": 90.0692840647,
        "Batting Average": 52.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 288.0,
        "Player Points": 61.349967924,
        "Value": 650000.0
    },
    {
        "Name": "Kalana Samarawickrama",
        "University": "Eastern University",
        "Category": "Batsman",
        "Strike Rate": 90.099009901,
        "Batting Average": 52.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 288.0,
        "Player Points": 61.3559130913,
        "Value": 650000.0
    },
    {
        "Name": "Lakshan Vandersay",
        "University": "University of the Visual & Performing Arts",
        "Category": "All-Rounder",
        "Strike Rate": 120.178041543,
        "Batting Average": 27.0,
        "Bowling Strike Rate": 30.0,
        "Economy Rate": 216.0,
        "Player Points": 28.3207934938,
        "Value": 350000.0
    },
    {
        "Name": "Roshen Samarawickrama",
        "University": "University of Kelaniya",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 10.0,
        "Bowling Strike Rate": 18.2608695652,
        "Economy Rate": 144.0,
        "Player Points": 10.3531746032,
        "Value": 200000.0
    },
    {
        "Name": "Sammu Sandakan",
        "University": "University of Ruhuna",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 12.0,
        "Bowling Strike Rate": 18.4615384615,
        "Economy Rate": 144.0,
        "Player Points": 8.4555555556,
        "Value": 200000.0
    },
    {
        "Name": "Kalana Jayawardene",
        "University": "University of Jaffna",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 12.0,
        "Bowling Strike Rate": 18.1818181818,
        "Economy Rate": 144.0,
        "Player Points": 8.8722222222,
        "Value": 200000.0
    },
    {
        "Name": "Binura Samarawickrama",
        "University": "University of the Visual & Performing Arts",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 11.0,
        "Bowling Strike Rate": 18.0,
        "Economy Rate": 144.0,
        "Player Points": 9.95,
        "Value": 200000.0
    },
    {
        "Name": "Dasun Thirimanne",
        "University": "Eastern University",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 11.0,
        "Bowling Strike Rate": 18.2068965517,
        "Economy Rate": 180.0,
        "Player Points": 9.4398989899,
        "Value": 200000.0
    },
    {
        "Name": "Angelo Samarawickrama",
        "University": "University of Kelaniya",
        "Category": "Batsman",
        "Strike Rate": 90.0212314225,
        "Batting Average": 53.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 252.0,
        "Player Points": 62.3883732686,
        "Value": 650000.0
    },
    {
        "Name": "Nuwan Jayawickrama",
        "University": "University of Ruhuna",
        "Category": "Batsman",
        "Strike Rate": 90.0900900901,
        "Batting Average": 50.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 59.5612278946,
        "Value": 650000.0
    },
    {
        "Name": "Kusal Dhananjaya",
        "University": "South Eastern University",
        "Category": "Batsman",
        "Strike Rate": 90.0562851782,
        "Batting Average": 48.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 288.0,
        "Player Points": 58.1473681468,
        "Value": 600000.0
    },
    {
        "Name": "Chamika Bandara",
        "University": "Eastern University",
        "Category": "Batsman",
        "Strike Rate": 90.0,
        "Batting Average": 54.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 62.7432098765,
        "Value": 650000.0
    },
    {
        "Name": "Dilruwan Shanaka",
        "University": "University of Peradeniya",
        "Category": "Batsman",
        "Strike Rate": 90.1408450704,
        "Batting Average": 48.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 57.9713788906,
        "Value": 600000.0
    },
    {
        "Name": "Danushka Jayawickrama",
        "University": "University of Peradeniya",
        "Category": "All-Rounder",
        "Strike Rate": 120.2749140893,
        "Batting Average": 25.0,
        "Bowling Strike Rate": 30.0,
        "Economy Rate": 180.0,
        "Player Points": 26.6105383734,
        "Value": 350000.0
    },
    {
        "Name": "Charith Shanaka",
        "University": "University of Colombo",
        "Category": "Batsman",
        "Strike Rate": 90.0,
        "Batting Average": 53.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 61.9432098765,
        "Value": 650000.0
    },
    {
        "Name": "Asela Nissanka",
        "University": "University of Sri Jayewardenepura",
        "Category": "Batsman",
        "Strike Rate": 90.0,
        "Batting Average": 51.0,
        "Bowling Strike Rate": null,
        "Economy Rate": 0.0,
        "Player Points": null,
        "Value": null
    },
    {
        "Name": "Wanindu Hasaranga",
        "University": "University of Colombo",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 12.0,
        "Bowling Strike Rate": 18.0,
        "Economy Rate": 216.0,
        "Player Points": 8.8259259259,
        "Value": 200000.0
    },
    {
        "Name": "Asela Vandersay",
        "University": "University of the Visual & Performing Arts",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 11.0,
        "Bowling Strike Rate": 18.1621621622,
        "Economy Rate": 144.0,
        "Player Points": 9.701984127,
        "Value": 200000.0
    },
    {
        "Name": "Pathum Fernando",
        "University": "University of Peradeniya",
        "Category": "Batsman",
        "Strike Rate": 90.0,
        "Batting Average": 45.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 55.5432098765,
        "Value": 600000.0
    },
    {
        "Name": "Angelo Kumara",
        "University": "Eastern University",
        "Category": "Batsman",
        "Strike Rate": 90.1639344262,
        "Batting Average": 55.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 288.0,
        "Player Points": 63.7688979964,
        "Value": 650000.0
    },
    {
        "Name": "Danushka Rajapaksa",
        "University": "University of Peradeniya",
        "Category": "Batsman",
        "Strike Rate": 90.0,
        "Batting Average": 49.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 252.0,
        "Player Points": 59.1841269841,
        "Value": 650000.0
    },
    {
        "Name": "Suranga Shanaka",
        "University": "South Eastern University",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 11.0,
        "Bowling Strike Rate": 18.4615384615,
        "Economy Rate": 144.0,
        "Player Points": 9.2555555556,
        "Value": 200000.0
    },
    {
        "Name": "Pathum Dhananjaya",
        "University": "Eastern University",
        "Category": "Batsman",
        "Strike Rate": 90.0,
        "Batting Average": 45.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 55.5432098765,
        "Value": 600000.0
    },
    {
        "Name": "Asela Asalanka",
        "University": "South Eastern University",
        "Category": "Batsman",
        "Strike Rate": 90.0163666121,
        "Batting Average": 50.0,
        "Bowling Strike Rate": null,
        "Economy Rate": 0.0,
        "Player Points": null,
        "Value": null
    },
    {
        "Name": "Minod Rathnayake",
        "University": "University of Kelaniya",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 11.0,
        "Bowling Strike Rate": 18.1621621622,
        "Economy Rate": 144.0,
        "Player Points": 9.701984127,
        "Value": 200000.0
    },
    {
        "Name": "Binura Lakmal",
        "University": "University of Kelaniya",
        "Category": "Batsman",
        "Strike Rate": 90.0,
        "Batting Average": 45.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 288.0,
        "Player Points": 55.7361111111,
        "Value": 600000.0
    },
    {
        "Name": "Praveen Asalanka",
        "University": "Eastern University",
        "Category": "Batsman",
        "Strike Rate": 90.0,
        "Batting Average": 53.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 252.0,
        "Player Points": 62.3841269841,
        "Value": 650000.0
    },
    {
        "Name": "Angelo Jayawardene",
        "University": "University of Jaffna",
        "Category": "Batsman",
        "Strike Rate": 90.0,
        "Batting Average": 52.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 252.0,
        "Player Points": 61.5841269841,
        "Value": 650000.0
    },
    {
        "Name": "Kamindu Asalanka",
        "University": "University of Moratuwa",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 9.0,
        "Bowling Strike Rate": 18.0,
        "Economy Rate": 216.0,
        "Player Points": 11.2259259259,
        "Value": 200000.0
    },
    {
        "Name": "Sadeera Rajapaksa",
        "University": "University of Jaffna",
        "Category": "All-Rounder",
        "Strike Rate": 120.0873362445,
        "Batting Average": 25.0,
        "Bowling Strike Rate": 33.0,
        "Economy Rate": 216.0,
        "Player Points": 28.2178039492,
        "Value": 350000.0
    },
    {
        "Name": "Sandakan Hasaranga",
        "University": "University of Kelaniya",
        "Category": "Batsman",
        "Strike Rate": 90.0339750849,
        "Batting Average": 53.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 252.0,
        "Player Points": 62.3909220011,
        "Value": 650000.0
    },
    {
        "Name": "Bhanuka Rajapaksa",
        "University": "University of Moratuwa",
        "Category": "All-Rounder",
        "Strike Rate": 120.1320132013,
        "Batting Average": 26.0,
        "Bowling Strike Rate": 30.5454545455,
        "Economy Rate": 216.0,
        "Player Points": 27.8092068731,
        "Value": 350000.0
    },
    {
        "Name": "Chamika Rajapaksa",
        "University": "University of Ruhuna",
        "Category": "Batsman",
        "Strike Rate": 90.0,
        "Batting Average": 50.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 252.0,
        "Player Points": 59.9841269841,
        "Value": 650000.0
    },
    {
        "Name": "Kamindu Lakmal",
        "University": "University of the Visual & Performing Arts",
        "Category": "Batsman",
        "Strike Rate": 90.0692840647,
        "Batting Average": 52.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 252.0,
        "Player Points": 61.5979837971,
        "Value": 650000.0
    },
    {
        "Name": "Lakshan Gunathilaka",
        "University": "University of Peradeniya",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 12.0,
        "Bowling Strike Rate": 18.0,
        "Economy Rate": 180.0,
        "Player Points": 8.9555555556,
        "Value": 200000.0
    },
    {
        "Name": "Tharindu Thirimanne",
        "University": "South Eastern University",
        "Category": "Batsman",
        "Strike Rate": 90.1179941003,
        "Batting Average": 47.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 57.1668086966,
        "Value": 600000.0
    },
    {
        "Name": "Dinesh Samarawickrama",
        "University": "University of Jaffna",
        "Category": "Batsman",
        "Strike Rate": 90.0900900901,
        "Batting Average": 50.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 59.5612278946,
        "Value": 650000.0
    },
    {
        "Name": "Suranga Sandakan",
        "University": "University of Moratuwa",
        "Category": "Batsman",
        "Strike Rate": 90.0383141762,
        "Batting Average": 47.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 57.1508727118,
        "Value": 600000.0
    },
    {
        "Name": "Sandakan Dickwella",
        "University": "University of Jaffna",
        "Category": "Batsman",
        "Strike Rate": 90.1960784314,
        "Batting Average": 46.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 324.0,
        "Player Points": 56.3824255628,
        "Value": 600000.0
    },
    {
        "Name": "Sammu Rajapaksa",
        "University": "University of Ruhuna",
        "Category": "Batsman",
        "Strike Rate": 90.2255639098,
        "Batting Average": 48.0,
        "Bowling Strike Rate": 0.0,
        "Economy Rate": 288.0,
        "Player Points": 58.1812238931,
        "Value": 600000.0
    },
    {
        "Name": "Suranga Bandara",
        "University": "University of Moratuwa",
        "Category": "Bowler",
        "Strike Rate": 50.0,
        "Batting Average": 11.0,
        "Bowling Strike Rate": 18.2608695652,
        "Economy Rate": 216.0,
        "Player Points": 9.2291005291,
        "Value": 200000.0
    },
    {
        "Name": "Tharindu Embuldeniya",
        "University": "University of the Visual & Performing Arts",
        "Category": "All-Rounder",
        "Strike Rate": 120.0,
        "Batting Average": 22.0,
        "Bowling Strike Rate": 30.0,
        "Economy Rate": 216.0,
        "Player Points": 24.2851851852,
        "Value": 300000.0
    }
]